name: airflow 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - airflow=1.10.1
  - sshtunnel
  - flask-cors
  - flower
  - celery
  - ipython
  - airflow-with-postgres
  - psycopg2
  - paramiko
